version: "3"
services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - "/home/yoonsele/data/wp:/var/www/html"
    depends_on:
      - wordpress
    networks:
      - inception-network
    restart: always

  wordpress:
    build: requirements/wordpress/
    container_name: wordpress
    ports:
      - "9000:9000"
    volumes:
      - "/home/yoonsele/data/wp:/var/www/html"
    depends_on:
      - mariadb
    networks:
      - inception-network
    restart: always
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USR: ${WP_DB_USR}
      WP_DB_PWD: ${WP_DB_PWD}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USR: ${WP_ADMIN_USR}
      WP_ADMIN_PWD: ${WP_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USR: ${WP_USR}
      WP_USR_PWD: ${WP_USR_PWD}
      WP_USR_EMAIL: ${WP_USR_EMAIL}

  mariadb:
    build: requirements/mariadb/
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - "/home/yoonsele/data/db:/var/lib/mysql"
    networks:
      - inception-network
    restart: always
    environment:
      MYSQL_ROOT_PWD: ${MYSQL_ROOT_PWD}
      WP_DB_NAME: ${WP_DB_NAME}
      WP_DB_USR: ${WP_DB_USR}
      WP_DB_PWD: ${WP_DB_PWD}

networks:
  inception-network:
